CREATE TABLE `product` (
  `product_id` int(11) NOT NULL AUTO_INCREMENT,
  `sku` varchar(45) DEFAULT NULL,
  `title` varchar(255) DEFAULT NULL,
  `brand_code` varchar(45) DEFAULT NULL,
  `brand_name` varchar(100) DEFAULT NULL,
  `description` text,
  `how_to_use` text,
  `ingredients` text,
  `language_code` enum('en_US') DEFAULT 'en_US',
  `category_id` int(11) DEFAULT NULL,
  `currency_code` enum('SGD','EUR') DEFAULT NULL,
  `retail_price` decimal(10,2) DEFAULT NULL,
  `selling_price` decimal(10,2) DEFAULT NULL,
  `qty` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`product_id`),
  KEY `fk_brand_idx` (`brand_code`),
  KEY `fk_category_idx` (`category_id`),
  KEY `prdt_title_idx` (`title`),
  KEY `prdt_retail_price_idx` (`retail_price`),
  KEY `prdt_selling_price_idx` (`selling_price`),
  KEY `prdt_lang_code_idx` (`language_code`),
  KEY `prdt_sku_idx` (`sku`),
  CONSTRAINT `fk_brand` FOREIGN KEY (`brand_code`) REFERENCES `brand` (`brand_code`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_category` FOREIGN KEY (`category_id`) REFERENCES `category` (`category_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8